SELECT 
    AI.ANIMAL_ID,
    AI.ANIMAL_TYPE,
    AO.NAME
FROM ANIMAL_INS AS AI
JOIN ANIMAL_OUTS AS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE LIKE "%Intact%" AND 
(
    AO.SEX_UPON_OUTCOME LIKE "%Spayed%" OR
    AO.SEX_UPON_OUTCOME LIKE "%Neutered%"
)