WITH RENTAL_INFO AS (
    SELECT 
        C.DAILY_FEE,
        C.CAR_TYPE,
        RH.HISTORY_ID,
        DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD,
        CASE 
          WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
          WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
          WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE 'NONE' 
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
    JOIN CAR_RENTAL_COMPANY_CAR AS C
    ON C.CAR_ID = RH.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT 
    HISTORY_ID,
    ROUND(
        RI.DAILY_FEE * RI.PERIOD * (100 - IFNULL(DP.DISCOUNT_RATE,0)) / 100  
    ) AS FEE
FROM RENTAL_INFO AS RI
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
ON RI.DURATION_TYPE = DP.DURATION_TYPE AND RI.CAR_TYPE = DP.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
