SELECT 
    MONTH(START_DATE) AS MONTH, 
    CAR_ID,
    COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- 8월부터 10월까지 5회 이상 대여한 자동차
WHERE CAR_ID IN 
(
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
-- 다른 날짜에 대한 자동차 아이디가 들어가면 안되기 때문에
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC