SELECT DISTINCT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CCRH
ON CRCC.CAR_ID = CCRH.CAR_ID
WHERE CAR_TYPE = "세단" AND MONTH(START_DATE) = "10"
ORDER BY CAR_ID DESC